---
- hosts: coopdevs
  remote_user: ubuntu
  become: yes

  vars:
    - sites_dir: /opt/sites

  roles:
    - common
    - http-server
    - coopdevs.org
    - role: vendor/geerlingguy.postgresql
    - role: limesurvey
      vars:
        - limesurvey_base_dir: "{{ sites_dir }}"
        - limesurvey_dir: "{{ limesurvey_base_dir }}/limesurvey"
        - limesurvey_user: limesurvey
        - limesurvey_group: limesurvey
