---
- name: Download limesurvey compressed archive
  get_url:
    url: https://www.limesurvey.org/stable-release?download=2149:limesurvey2722%20171017targz
    dest: /tmp/limesurvey.tar.gz
    checksum: sha256:fdca4c9193447277afeedd70b9ddad91b8e44c9a1091e3f633cca1cdd51c8916

- name: Create user and group
  user:
    name: "{{ limesurvey_user }}"

- name: Decompress limesurvey
  unarchive:
    src: /tmp/limesurvey.tar.gz
    dest: "{{ limesurvey_base_dir }}"
    remote_src: true
    owner: "{{ limesurvey_user }}"
    group: "{{ limesurvey_group }}"
    mode: 2755
