---
- name: Install Bundler gem
  gem:
    name: bundler
    state: latest
    user_install: no
    executable: "/usr/bin/gem2.3"

- name: Install Jekyll gem
  gem:
    name: jekyll
    state: latest
    user_install: no
    executable: "/usr/bin/gem2.3"
