---
- name: Add BrightBox ruby ppa
  apt_repository: repo=ppa:brightbox/ruby-ng state=present

- name: Install BrightBox ruby 2.3 package
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - 'software-properties-common'
    - 'ruby2.3'
    - 'ruby2.3-dev'
