#!/bin/bash -l
GIT_REPO=$HOME/repos/coopdevs.github.io.git
TMP_GIT_CLONE=$HOME/tmp/git/coopdevs.github.io
PUBLIC_WWW=/opt/sites/coopdevs

git clone $GIT_REPO $TMP_GIT_CLONE
jekyll build --source $TMP_GIT_CLONE --destination $PUBLIC_WWW
rm -Rf $TMP_GIT_CLONE
exit
